### ISSUE TITLE
电话亭动画&望远镜没有换色

### ISSUE THREAD

**Issue by ZTL-UwU** [Vinceli2401/celeste-skin-creator#1]
[Graphics](https://github.com/Vinceli2401/CelesteSkinModCreator/tree/main/SkinBase/Graphics)/[Atlases](https://github.com/Vinceli2401/CelesteSkinModCreator/tree/main/SkinBase/Graphics/Atlases)/[Gameplay](https://github.com/Vinceli2401/CelesteSkinModCreator/tree/main/SkinBase/Graphics/Atlases/Gameplay)/[Author](https://github.com/Vinceli2401/CelesteSkinModCreator/tree/main/SkinBase/Graphics/Atlases/Gameplay/Author)/Skin/ 下应该还有 `cutscenes/payphone` 和 `objects/lookout`

**Comment by Vinceli2401** [comment]
这下寄，在处理了

**Comment by Vinceli2401** [comment]
Sorry for the two-year delay. This has now been fixed.
